resources:
  - fpga-reader-clusterrole.yaml
  - intel-fpga-webhook-deployment.yaml
  - intel-fpga-webhook-svc.yaml
  - fpga-mutator-webhook-cfg.yaml
  - region-crd.yaml
  - acceleratorfunction-crd.yaml
  - mappings-collection.yaml

configurations:
  - kustomize-varreference.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: intel-fpga-webhook-certs
    files:
      - key.pem=intel-fpga-webhook-certs-secret/key.pem
      - cert.pem=intel-fpga-webhook-certs-secret/cert.pem
      - client-ca-file=intel-fpga-webhook-certs-secret/client-ca-file

vars:
  - name: CA_BUNDLE
    objref:
      kind: Secret
      version: v1
      name: intel-fpga-webhook-certs
    fieldref:
      fieldpath: data[client-ca-file]
