apiVersion: v1
kind: ServiceAccount
metadata:
  name: intel-fpga-plugin-controller
  namespace: {namespace}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-getter
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: get-nodes
subjects:
- kind: ServiceAccount
  name: intel-fpga-plugin-controller
  namespace: {namespace}
roleRef:
  kind: ClusterRole
  name: node-getter
  apiGroup: rbac.authorization.k8s.io
