bases:
  - ../../base
  - ../../../fpga_admissionwebhook/base

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: intel-fpga-plugin
    path:
      change-mode-region.yaml
